zeebe-cluster-helm:
  global:
    zeebe: "zeebe-zeebe"
    elasticsearch:
      host: "zeebe-elasticsearch"

  image:
    repository: camunda/zeebe
    tag: 1.1.0

  clusterSize: "1"
  partitionCount: "1"
  replicationFactor: "1"
  cpuThreadCount: "2"
  ioThreadCount: "2"
  pvcSize: "10Gi"
  pvcAccessModes:
    - "ReadWriteOnce"

  resources:
    requests:
      cpu: 100m

  env:
    #    - name: ZEEBE_BROKER_BACKPRESSURE_ENABLED
    #      value: "false"
    - name: ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED
      value: "true"
    #    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME
    #      value: "hu.dpc.rt.kafkastreamer.exporter.NoOpExporter"
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_JARPATH
      value: "/exporters/ph-ee-kafka-exporter.jar"
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_JARPATH
      value: "/exporters/ph-ee-kafka-exporter.jar"
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_CLASSNAME
      value: "hu.dpc.rt.kafkastreamer.exporter.KafkaExporter"
    - name: ZEEBE_BROKER_BACKPRESSURE_VEGAS_INITIALLIMIT
      value: "1000"
    - name: ZEEBE_BROKER_BACKPRESSURE_VEGAS_ALPHA
      value: "2"
    - name: ZEEBE_BROKER_BACKPRESSURE_VEGAS_BETA
      value: "8"

  gateway:
    replicas: 1
    logLevel: warn
    env:
      - name: ZEEBE_GATEWAY_THREADS_MANAGEMENTTHREADS
        value: "4"
      - name: ZEEBE_GATEWAY_MONITORING_ENABLED
        value: "true"

  # zeebe's dependencies
  elasticsearch:
    enabled: false
    fullnameOverride: "zeebe-elasticsearch"
    clusterName: "zeebe-elasticsearch"

  kibana:
    enabled: false
    fullnameOverride: "zeebee-kibana"
    elasticsearchHosts: "http://zeebe-elasticsearch:9200/"

  prometheus:
    enabled: false

  extraInitContainers: |
    - name: init-ph-ee-kafka-exporter
      image: busybox:1.28
      command: ['/bin/sh', '-c']
      args: ['wget -O /exporters/ph-ee-kafka-exporter.jar "https://paymenthub-ee-dev.s3.us-east-2.amazonaws.com/jars/exporter-1.0.0-SNAPSHOT.jar"; ls -al /exporters/']
      volumeMounts:
      - name: exporters
        mountPath: /exporters/

# payment hub Operate, ES and Kibana
zeebe-operate-helm:
  enabled: false
  image:
    repository: camunda/operate
    tag: 1.1.0
  fullnameOverride: "zeebe-operate"
  global:
    zeebe: "zeebe-zeebe"
    elasticsearch:
      host: "zeebe-elasticsearch"
      clusterName: "zeebe-elasticsearch"

  elasticsearch:
    enabled: true
    replicas: 1
    minimumMasterNodes: 1
    imageTag: 7.16.3

    # Single Node Solution
    clusterHealthCheckParams: "wait_for_status=yellow&timeout=100s"
    master:
      readinessProbe:
        httpGet:
          path: /_cluster/health?wait_for_status=yellow&timeout=5s
          port: 9200
        initialDelaySeconds: 30
    data:
      readinessProbe:
        httpGet:
          path: /_cluster/health?wait_for_status=yellow&timeout=5s
          port: 9200
        initialDelaySeconds: 30

    # Shrink default JVM heap.
    esJavaOpts: "-Xmx512m -Xms512m"

    # Allocate smaller chunks of memory per pod.
    resources:
      requests:
        cpu: "200m"
        memory: "1024M"
      limits:
        cpu: "1000m"
        memory: "1024M"
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      storageClassName: oaf-storage
      resources:
        requests:
          storage: 10Gi

kibana:
  enabled: true
  imageTag: 7.16.3
  ingress:
    enabled: false
    className: "nginx"
    pathtype: ImplementationSpecific
    hosts:
      - host: ph-kibana.test.oneacrefund.org
        paths:
          - path: /
    tls:
      - secretName: oafqa-tls
        hosts:
          - "*.test.oneacrefund.org"
  kibanaConfig:
    kibana.yml: |
      monitoring.enabled: false

channel:
  enabled: true
  DFSPIDS: "oaf"
  transaction_id_length: 20
  SPRING_PROFILES_ACTIVE: "bb"
  LOGGING_LEVEL_ROOT: "INFO"
  hostname: "paymenthub.qa.oneacrefund.org"
  AWS_ACCESS_KEY: "xxx"
  AWS_SECRET_KEY: "xxx"
  image: "oaftech.azurecr.io/phee-ns/ph-ee-connector-channel"
  ams:
    groups: ""
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: "kong"
      konghq.com/strip-path: "true"
    backend:
      service:
        name: ph-ee-connector-channel
        port:
          number: 80
  limits:
    memory: "768M"
    cpu: "500m"
  requests:
    memory: "768M"
    cpu: "200m"
    path: "/channel"
    annotations: {}
    backend: {}
  deployment:
    annotations: {}

operations:
  enabled: true

ingress:
  apiversion: "networking.k8s.io/v1"

deployment:
  apiversion: "apps/v1"

service:
  apiversion: "v1"

secret:
  apiversion: "v1"

configmap:
  apiversion: "v1"

operationsmysql:
  enabled: false
  ingress:
    enabled: false
  fullnameOverride: "operationsmysql"
  image:
    tag: "5.7"
    debug: false
  auth:
    database: "tenants"
    username: "mifos"
    password: "password"
    rootPassword: "4ET6ywqlGt"
  initdbScripts:
    setup.sql: |-
      CREATE DATABASE IF NOT EXISTS oaf;
      CREATE DATABASE IF NOT EXISTS messagegateway;
      GRANT ALL ON *.* TO 'root'@'%';
      GRANT ALL PRIVILEGES ON messagegateway.* TO 'mifos';
      GRANT ALL PRIVILEGES ON oaf.* TO 'mifos';

operations_app:
  ingress:
    enabled: false
  enabled: true
  replicas: 1
  image: "oaftech.azurecr.io/phee-ns/ph-ee-operations-app"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  LOGGING_LEVEL_ROOT: "INFO"
  hostname: ""
  tenants: ""
  token_client_channel_secret: ""
  datasource:
    username: ""
    password: "secretPassword"
    host: ""
    port: 3306
    schema: ""
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "200m"
    path: "/opsapp"
    annotations: {}
    backend: {}
  deployment:
    annotations: {}

operations_web:
  ingress:
    enabled: false
  enabled: true
  replicas: 1
  image: ""
  imagePullPolicy: "Always"
  hostname: ""
  webhost: ""
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "200m"
    path: "/"
    annotations: {}
    backend: {}
  deployment:
    annotations: {}

identity:
  hostname: ""

mpesa:
  ingress:
    enabled: false
  enabled: true
  replicas: 1
  image: "oaftech.azurecr.io/phee-ns/ph-ee-connector-mpesa:v1.0.1"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  LOGGING_LEVEL_ROOT: "INFO"
  hostname: ""
  zeebe_broker_contactpoint: ""
  tenant: ""
  callback_host: ""
  business_short_code: ""
  till_number: ""
  retry_count: 1
  safaricom:
    auth_host: ""
    api_host: ""
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "200m"
    path: "/mpesa"
    annotations: {}
    backend: {}
  deployment:
    annotations: {}
  secret:
    value:
      client_key: "secretKey"
      client_secret: "secretClientSecret"
      pass_key: "secretPassKey"
      api_key: "secretApiKey"

roster_connector:
  LOGGING_LEVEL_ROOT: "INFO"
  ingress:
    enabled: false
  enabled: true
  replicas: 1
  image: "oaftech.azurecr.io/phee-ns/ph-ee-connector-ams-pesa:v1.0.0"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  containerPort: 5000
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "200m"
  ams:
    local:
      enabled: ""
  pesacore:
    auth_header: "secretAuthHeader"
    base_url: ""
  deployment:
    annotations: {}

messagegateway:
  ingress:
    enabled: false
  enabled: true
  replicas: 1
  image: "oaftech.azurecr.io/phee-ns/message-gateway:34d94ccc09"
  imagePullPolicy: "Always"
  LOGGING_LEVEL_ROOT: "INFO"
  hostname: ""
  CALLBACKCONFIG_HOST: "ph-ee-connector-notifications"
  HOSTCONFIG_HOST: ""
  MYSQL_USERNAME: "mifos"
  MYSQL_PASSWORD: "password"
  DATASOURCE_URL: ""
  PROVIDERSOURCE_FROMDATABASE: ""
  PROVIDERSOURCE_FROMYML: ""
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "200m"
    path: "/messages"
    annotations: {}
    backend: {}
  secret:
    value:
      api_key: ""
      project_id: ""
      key:
        telerivet_api_key: ""
  deployment:
    annotations: {}

notifications:
  ingress:
    enabled: false
  enabled: true
  replicas: 1
  image: "oaftech.azurecr.io/phee-ns/ph-ee-notifications:v1.0.1"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  LOGGING_LEVEL_ROOT: "INFO"
  hostname: ""
  zeebe_broker_contactpoint: ""
  NOTIFICATION_LOCAL_HOST: ""
  MESSAGEGATEWAYCONFIG_HOST: ""
  NOTIFICATION_SUCCESS_ENABLED: false
  NOTIFICATION_FAILURE_ENABLED: false
  hostconfig:
    host: ""
    port: ""
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "200m"
    path: "/notifications"
    annotations: {}
    backend: {}
  deployment:
    annotations: {}

zeebe_ops:
  ingress:
    enabled: false
  enabled: true
  replicas: 1
  image: "oaftech.azurecr.io/phee-ns/phee-zeebe-ops"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  LOGGING_LEVEL_ROOT: "INFO"
  hostname: ""
  zeebe_broker_contactpoint: ""
  tenants: ""
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "200m"
    path: "/zeebeops"
    annotations: {}
    backend: {}
  deployment:
    annotations: {}

importer_es:
  ingress:
    enabled: false
  replicas: 1
  image: "oaftech.azurecr.io/phee-ns/ph-ee-importer-es"
  imagePullPolicy: "Always"
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "200m"

kafka:
  enabled: true
  replicas: 1
  image: "spotify/kafka"
  imagePullPolicy: "Always"
  advertised:
    host: ""
    port: ""
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "200m"
  deployment:
    annotations: {}

importer_rdbms:
  enabled: true
  replicas: 1
  image: "oaftech.azurecr.io/phee-ns/ph-ee-importer-rdbms"
  imagePullPolicy: "Always"
  LOGGING_LEVEL_ROOT: "INFO"
  datasource:
    username: ""
    password: "secretPassword"
    host: ""
    port: 3306
    schema: ""
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "200m"
  deployment:
    annotations: {}

wildcardhostname: ""

tls: ""
