apiVersion: apps/v1
kind: Deployment
metadata:
  name: "message-gateway"
  labels:
    app: message-gateway
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/ph-ee-config.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-gateway
  template:
    metadata:
      labels:
        app: message-gateway
    spec:
      initContainers:
        - name: wait-db
          image: jwilder/dockerize
          imagePullPolicy: IfNotPresent
          args:
          - -timeout=120s
          - -wait
          - tcp://operations-mysql:3306
      containers:
        - name: message-gateway
          image: "{{ .Values.messagegateway.image }}"
          ports:
            - containerPort: 9191
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512M"
          env:
            - name: spring.datasource.url
              value: jdbc:mysql:thin://operations-mysql:3306/messagegateway
            - name: spring.datasource.username
              value: "mifos"
            - name: spring.datasource.password
              value: "password"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: message-gateway
  name: message-gateway
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 9191
  selector:
    app: message-gateway
  sessionAffinity: None
  type: ClusterIP