{{- if .Values.operations.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-operations-app"
  labels:
    app: ph-ee-operations-app
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/ph-ee-config.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-operations-app
  template:
    metadata:
      labels:
        app: ph-ee-operations-app
    spec:
      initContainers:
        - name: wait-db
          image: jwilder/dockerize
          imagePullPolicy: IfNotPresent
          args:
          - -timeout=120s
          - -wait
          - tcp://operations-mysql:3306
      containers:
        - name: ph-ee-operations-app
          image: "{{ .Values.operations_app.image }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /oauth/token_key
              port: 5000
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            limits:
              memory: "512M"
          env:
            - name: "FINERACT_DATASOURCE_CORE_USERNAME"
              value: "mifos"
            - name: "FINERACT_DATASOURCE_CORE_PASSWORD"
              value: "password"
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.operations_app.SPRING_PROFILES_ACTIVE }}"
            - name: "token.client.channel.secret"
              value: "p1234"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ph-ee-operations-app
  name: ph-ee-operations-app
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-operations-app
  sessionAffinity: None
  type: ClusterIP

{{- end }}
