{{- if .Values.operations.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-ee-operations-web
  labels:
    app: ph-ee-operations-web
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/ph-ee-config.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-operations-web
  template:
    metadata:
      labels:
        app: ph-ee-operations-web
    spec:
      initContainers:
        - name: wait-db
          image: jwilder/dockerize
          imagePullPolicy: IfNotPresent
          args:
          - -timeout=120s
          - -wait
          - tcp://operations-mysql:3306
      containers:
        - name: ph-ee-operations-web
          image: "{{ .Values.operations_web.image }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 4200
          volumeMounts:
            - name: ph-ee-operations-web-config
              mountPath: "/app/src/assets/configuration.properties"
              subPath: "configuration.properties"
      volumes:
        - name: ph-ee-operations-web-config
          configMap:
            name: ph-ee-operations-web-config

---
apiVersion: v1
data:
  configuration.properties: |
    oauth.enabled true
    oauth.basicAuth true
    oauth.basicAuthToken Y2xpZW50Og==
    oauth.serverUrl http://{{ .Values.identity.hostname }}
    serverUrl http://{{ .Values.operations_app.hostname }}
kind: ConfigMap
metadata:
  name: ph-ee-operations-web-config

---
kind: Service
apiVersion: v1
metadata:
  name: ph-ee-operations-web
spec:
  selector:
    app: ph-ee-operations-web
  ports:
    - protocol: TCP
      port: 4200

{{- end }}
