apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-zeebe-ops"
  labels:
    app: ph-ee-zeebe-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-zeebe-ops
  template:
    metadata:
      labels:
        app: ph-ee-zeebe-ops
      annotations:
        deployTime: "{{ .Values.deployTime }}"
    spec:
      containers:
        - name: ph-ee-zeebe-ops
          image: "{{ .Values.zeebe_ops.image }}"
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512M"
          ports:
            - containerPort: 5000
          env:
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "zeebe-zeebe-gateway:26500"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ph-ee-zeebe-ops
  name: ph-ee-zeebe-ops
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-zeebe-ops
  sessionAffinity: None
  type: ClusterIP
  